## TechX 2020 计算社科预习 Quiz 2 V1.0 (Score: 28/30)

这个测试的目的不是为了难倒大家，而是为了检验预习成果，方便我们调整接下来的预习和课程安排。同时，我们也希望你们能通过这几个练习学到的知识，并学到的coding技巧。因此，我们有如下要求：
1. 虽然我们不允许大家向别人请教 quiz 中的问题，但是你们可以在互联网上搜索已有的资源：这也是在TechX的学习过程中大家会一直做的。（PS 请别直接抄代码！请理解之后自己实现）
2. 有些题目里会给出一些变量/数据，但是我们批改的时候可能会改动它们以检测你程序的可拓展性。
3. 请在北京时间7.26 24:00之前在教学立方提交，如有事无法按时请私信自己的对应AL（在预习文档里 https://shimo.im/docs/eIy4MXRYkLoZvE2Z ）。
4. 如果感觉题目有问题或表述不清请直接在群里提出。我们有可能根据大家的提问发布V2.0 的 Quiz。

PS 问题保留了答案，但大家可以通过多种方式得到它们。

## 0. Setup  

请在下面导入numpy(用np代替)，以及pandas（用pd代替）

In [178]:
import numpy as np
import pandas as pd

## 1. Array Basics 
a. 创建一个shape为(10,10), 值为0~99的2D array，命名为x (应该和下图一样)
(Score:2/2)

In [163]:
x = np.arange(100).reshape(10, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

b. 用array slicing找出x中所有5的倍数，并输出为一维array (Score:2/2)

In [164]:
x[x%5==0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

c. 找出array x 右上角 shape = (4, 4) 的方块和左下角shape = (2,8)的长方形，把 vertically 他们拼接成一个 shape = (4, 8)的矩阵。把这个矩阵赋值为 y。(Score:2/2)

In [165]:
y = np.concatenate([x[:4, -4:], x[-2:, :8].reshape(4,4)])
y

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [90, 91, 92, 93],
       [94, 95, 96, 97]])

d. 给y的每个值都apply这个function: $$f(x) = 3 \cdot x + 7$$ (Score:1/2)

In [166]:
y = np.multiply(y, 3)
y = np.add(y, 3)   # Minor mistake
y

array([[ 21,  24,  27,  30],
       [ 51,  54,  57,  60],
       [ 81,  84,  87,  90],
       [111, 114, 117, 120],
       [243, 246, 249, 252],
       [255, 258, 261, 264],
       [273, 276, 279, 282],
       [285, 288, 291, 294]])

e. 创建一个和array x的shape相同的boolean mask, 每个位置的值为array x对应位置的值是否即使3的倍数又是5的倍数。把这个array称作z. (use one of / % //) (Score:2/2)

In [167]:
z = (x%3==0) & (x%5==0)

In [168]:
z.shape

(10, 10)

f. 通过z来选中x中符合这些条件的数。(Score:2/2)

In [169]:
x[z == True]

array([ 0, 15, 30, 45, 60, 75, 90])

# 2. Pandas Basics

a. 请一句话说明concat与 merge的区别 (Score:2/2)

答：concat是把两个拼接到一起，merge是根据index和信息融合dataframe

b. 用pandas导入 Data Science Handbook notebooks/data/中的 state-population.csv 文件，把它命名为df (Score:2/2)

In [170]:
CSV_FILE_PATH = "./state-population.csv"
df = pd.read_csv(CSV_FILE_PATH)

c. 展示df的shape，它有哪些column，每个column的data type是什么？(Score:2/2)

In [171]:
df.shape

(2544, 4)

In [172]:
df.columns

Index(['state/region', 'ages', 'year', 'population'], dtype='object')

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
state/region    2544 non-null object
ages            2544 non-null object
year            2544 non-null int64
population      2524 non-null float64
dtypes: float64(1), int64(1), object(2)
memory usage: 79.6+ KB


d. 展示第2301行（注意index是从0开始的）(Score:2/2)

In [174]:
df[2300:2301]

state/region     ages  year  population
2300           WA  under18  2011   1584709.0

e. 找到2002年伊利诺伊(code: IL)的总人口 (Score:2/2)

In [175]:
for i in range(len(df)):
    if df.loc[i, "state/region"] == "IL" and df.loc[i, "year"] == 2002 and df.loc[i, "ages"] == "total":
        print(df.iloc[i])

state/region             IL
ages                  total
year                   2002
population      1.25256e+07
Name: 646, dtype: object


f. 使用groupby等方法，计算2008年以及以后每个州18岁以下人口的平均值，输出前五个人口最多的（不包括USA，可以使用 df.sort_values()等函数 ）。(Score:2/2)

In [176]:
df[df["year"] >= 2008].groupby("state/region").agg("mean").sort_values("population")[-6:]

year    population
state/region                      
IL            2010.5  7.964491e+06
FL            2010.5  1.150333e+07
NY            2010.5  1.187334e+07
TX            2010.5  1.615111e+07
CA            2010.5  2.336972e+07
USA           2010.5  1.921110e+08

g. 找到每年总人口的maximum，minimum，以及median (用aggreagate)(Score:1/2)

In [177]:
df_new = df.groupby("year").agg({"population":"min"})
df_new["median"] = df.groupby("year").agg({"population":"median"})
df_new["max"] = df.groupby("year").agg({"population":"max"})
df_new.columns = ["min","median","max"]
df_new

# Incorrect rows selected. 

min     median          max
year                                  
1990  112632.0  1395507.5  249622814.0
1991  116825.0  1412934.5  252980942.0
1992  118636.0  1425919.0  256514231.0
1993  120471.0  1444365.5  259918595.0
1994  122170.0  1495550.0  263125826.0
1995  123620.0  1544747.0  266278403.0
1996  121210.0  1591054.0  269394291.0
1997  119531.0  1611518.0  272646932.0
1998  113839.0  1623888.5  275854116.0
1999  115003.0  1635421.5  279040181.0
2000  114503.0  1644404.5  282162411.0
2001  114625.0  1649681.5  284968955.0
2002  113822.0  1654553.0  287625193.0
2003  111403.0  1660601.5  290107933.0
2004  109756.0  1667825.5  292805298.0
2005  107187.0  1677697.5  295516599.0
2006  105651.0  1687900.0  298379912.0
2007  104126.0  1696467.0  301231207.0
2008  102257.0  1712514.5  304093966.0
2009  102098.0  1720013.0  306771529.0
2010  101309.0  1729200.5  309326295.0
2011  103906.0  1729051.0  311582564.0
2012  107642.0  1736249.5  313873685.0
2013  111474.0  1735559.0  316128839.0

h. 把df state/region  下的 IL 改成 Illinois (可以自己define一个function，也可以查询Python lambda function的使用)(Score:2/2)

In [161]:
for i in range(len(df)):
    if df.loc[i, "state/region"] == "IL":
        df.loc[i, "state/region"] = "Illinois"
df[df["state/region"] == "Illinois"]

state/region     ages  year  population
624     Illinois  under18  1990   2940837.0
625     Illinois    total  1990  11453316.0
626     Illinois    total  1991  11568964.0
627     Illinois  under18  1991   2988715.0
628     Illinois  under18  1994   3110938.0
629     Illinois    total  1994  11912585.0
630     Illinois    total  1993  11809579.0
631     Illinois  under18  1993   3066541.0
632     Illinois  under18  1992   3033427.0
633     Illinois    total  1992  11694184.0
634     Illinois    total  1995  12008437.0
635     Illinois  under18  1995   3152984.0
636     Illinois  under18  1996   3192916.0
637     Illinois    total  1996  12101997.0
638     Illinois  under18  1998   3225252.0
639     Illinois    total  1998  12271847.0
640     Illinois    total  1997  12185715.0
641     Illinois  under18  1997   3222114.0
642     Illinois    total  2000  12434161.0
643     Illinois  under18  2000   3244944.0
644     Illinois    total  1999  12359020.0
645     Illinois  under18  1999   3240034.0
646     Illinois    total  2002  12525556.0
647     Illinois  under18  2002   3238362.0
648     Illinois    total  2001  12488445.0
649     Illinois  under18  2001   3243617.0
650     Illinois    total  2004  12589773.0
651     Illinois  under18  2004   3211599.0
652     Illinois    total  2003  12556006.0
653     Illinois  under18  2003   3225547.0
654     Illinois    total  2006  12643955.0
655     Illinois  under18  2006   3181246.0
656     Illinois    total  2005  12609903.0
657     Illinois  under18  2005   3197318.0
658     Illinois    total  2008  12747038.0
659     Illinois  under18  2008   3153401.0
660     Illinois    total  2007  12695866.0
661     Illinois  under18  2007   3170134.0
662     Illinois  under18  2013   3023307.0
663     Illinois    total  2009  12796778.0
664     Illinois  under18  2009   3138406.0
665     Illinois    total  2013  12882135.0
666     Illinois    total  2010  12839695.0
667     Illinois  under18  2010   3122092.0
668     Illinois    total  2011  12855970.0
669     Illinois  under18  2011   3089833.0
670     Illinois  under18  2012   3057042.0
671     Illinois    total  2012  12868192.0

j. Do a brief but meaningful analysis to the US population data with the tools you learned. Remember to briefly explain it with comments.(Score:2/2)

In [ ]:
df_under_18 = df[df["ages"]=="under18"].groupby("year").agg({"population":"mean"})
df_total = df[df["ages"]=="total"].groupby("year").agg({"population":"mean"})
df_ratio = df_total/df_under_18
df_ratio#from the diagram below, the ratio of population under 18 years old proportion to the total population is increasing over years
#this suggest the ratio of working population is annually increase in the country.

# 反馈
如果你对这个quiz的难度，预习的进度，以及课程目前以来的任何方面有任何建议或者问题都欢迎写在下面！

In [ ]:
预习进度有一些紧张，我才看到3.06