# TechX 2020 计算社科预习 Quiz 2 V1.0  (Score: 28/30)

这个测试的目的不是为了难倒大家，而是为了检验预习成果，方便我们调整接下来的预习和课程安排。同时，我们也希望你们能通过这几个练习学到的知识，并学到的coding技巧。因此，我们有如下要求：
1. 虽然我们不允许大家向别人请教 quiz 中的问题，但是你们可以在互联网上搜索已有的资源：这也是在TechX的学习过程中大家会一直做的。（PS 请别直接抄代码！请理解之后自己实现）
2. 有些题目里会给出一些变量/数据，但是我们批改的时候可能会改动它们以检测你程序的可拓展性。
3. 请在北京时间7.26 24:00之前在教学立方提交，如有事无法按时请私信自己的对应AL（在预习文档里 https://shimo.im/docs/eIy4MXRYkLoZvE2Z ）。
4. 如果感觉题目有问题或表述不清请直接在群里提出。我们有可能根据大家的提问发布V2.0 的 Quiz。

PS 问题保留了答案，但大家可以通过多种方式得到它们。

## 0. Setup

请在下面导入numpy(用np代替)，以及pandas（用pd代替）

In [2]:
import numpy as np
import pandas as pd

## 1. Array Basics
a. 创建一个shape为(10,10), 值为0~99的2D array，命名为x (应该和下图一样)(Score:2/2) 

In [3]:
x=np.arange(0, 100).reshape((10,10))
print(x)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

b. 用array slicing找出x中所有5的倍数，并输出为一维array(Score:2/2)

In [39]:
x[0::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

c. 找出array x 右上角 shape = (4, 4) 的方块和左下角shape = (2,8)的长方形，把 vertically 他们拼接成一个 shape = (4, 8)的矩阵。把这个矩阵赋值为 y。(Score:2/2)

In [61]:
y

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [90, 91, 92, 93],
       [94, 95, 96, 97]])

d. 给y的每个值都apply这个function: $$f(x) = 3 \cdot x + 7$$(Score:2/2)

In [63]:
y

array([[ 25,  28,  31,  34],
       [ 55,  58,  61,  64],
       [ 85,  88,  91,  94],
       [115, 118, 121, 124],
       [247, 250, 253, 256],
       [259, 262, 265, 268],
       [277, 280, 283, 286],
       [289, 292, 295, 298]])

e. 创建一个和array x的shape相同的boolean mask, 每个位置的值为array x对应位置的值是否即使3的倍数又是5的倍数。把这个array称作z. (use one of / % //)(Score:1/2)

In [3]:
# Missing some code...

In [75]:
z.shape

(10, 10)

f. 通过z来选中x中符合这些条件的数。(Score:2/2)

array([ 0, 15, 30, 45, 60, 75, 90])

# 2. Pandas Basics

a. 请一句话说明concat与 merge的区别(Score:2/2)

答：concat是把两个拼接到一起，merge是根据index和信息融合dataframe

b. 用pandas导入 Data Science Handbook notebooks/data/中的 state-population.csv 文件，把它命名为df (Score:1/2)

In [2]:
path =r"E:\PythonDataScienceHandbook-master\notebooks\data\state-population.csv"
import pandas as pd
data =pd.read_csv(path,encoding="utf_8")
data.head(10) 
# Incorrect variable name... (df)

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
5           AL    total  2011   4801627.0
6           AL    total  2009   4757938.0
7           AL  under18  2009   1134192.0
8           AL  under18  2013   1111481.0
9           AL    total  2013   4833722.0

###### c. 展示df的shape，它有哪些column，每个column的data type是什么？(Score:2/2)

In [7]:
data.shape

(2544, 4)

In [8]:
data.columns

Index(['state/region', 'ages', 'year', 'population'], dtype='object')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   state/region  2544 non-null   object 
 1   ages          2544 non-null   object 
 2   year          2544 non-null   int64  
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 79.6+ KB


d. 展示第2301行（注意index是从0开始的）(Score:2/2)

In [14]:
data.iloc[2300,:]

state/region             WA
ages                under18
year                   2011
population      1.58471e+06
Name: 2300, dtype: object

e. 找到2002年伊利诺伊(code: IL)的总人口(Score:2/2)

In [26]:
data[(data["year"]==2002) & (data["state/region"]=="IL")&(data["ages"]=="total")]["population"].values

array([12525556.])

f. 使用groupby等方法，计算2008年以及以后每个州18岁以下人口的平均值，输出前五个人口最多的（不包括USA，可以使用 df.sort_values()等函数 ）。(Score:2/2)

In [34]:
datas = data[(data["ages"]=="under18")&(data["year"]>=2008)]["population"].groupby(data["state/region"]).mean()
result =datas.sort_values(ascending=False)
result[1:6]

state/region
CA    9.256073e+06
TX    6.884565e+06
NY    4.305392e+06
FL    4.009472e+06
IL    3.097347e+06
Name: population, dtype: float64

g. 找到每年总人口的maximum，minimum，以及median (用aggreagate)(Score:2/2)

In [36]:
import numpy as np
data[data["ages"]=="total"]["population"].groupby(data["year"]).agg([np.max, np.min, np.median])

amax      amin     median
year                                  
1990  249622814.0  453690.0  3404386.5
1991  252980942.0  459260.0  3478761.5
1992  256514231.0  466251.0  3558201.5
1993  259918595.0  473081.0  3638524.0
1994  263125826.0  480283.0  3714782.5
1995  266278403.0  485160.0  3787617.5
1996  269394291.0  488167.0  3857868.0
1997  272646932.0  489452.0  3906221.5
1998  275854116.0  490787.0  3952313.0
1999  279040181.0  491780.0  3996367.5
2000  282162411.0  494300.0  4024223.0
2001  284968955.0  494657.0  4064995.0
2002  287625193.0  500017.0  4089875.0
2003  290107933.0  503453.0  4117170.0
2004  292805298.0  509106.0  4146101.0
2005  295516599.0  514157.0  4182742.0
2006  298379912.0  522667.0  4219239.0
2007  301231207.0  534876.0  4256672.0
2008  304093966.0  546043.0  4289878.0
2009  306771529.0  559851.0  4317074.0
2010  309326295.0  564222.0  4347698.0
2011  311582564.0  567329.0  4366869.0
2012  313873685.0  576626.0  4379730.0
2013  316128839.0  582658.0  4395295.0

h. 把df state/region  下的 IL 改成 Illinois (可以自己define一个function，也可以查询Python lambda function的使用)(Score:2/2)

In [41]:
def trans(s):
    if s =="IL":
        return "Illinois"
    else:
        return s
data["state/region"] = data["state/region"].apply(trans)
data[data["state/region"]=="Illinois"].head(10)

state/region     ages  year  population
624     Illinois  under18  1990   2940837.0
625     Illinois    total  1990  11453316.0
626     Illinois    total  1991  11568964.0
627     Illinois  under18  1991   2988715.0
628     Illinois  under18  1994   3110938.0
629     Illinois    total  1994  11912585.0
630     Illinois    total  1993  11809579.0
631     Illinois  under18  1993   3066541.0
632     Illinois  under18  1992   3033427.0
633     Illinois    total  1992  11694184.0

j. Do a brief but meaningful analysis to the US population data with the tools you learned. Remember to briefly explain it with comments.(Score:2/2)

In [68]:
# function to caculate population percentage under18
def data_by_year(year):
    s1 =data[(data['year']==year)&(data["ages"]=="under18")].dropna(how="any").set_index("state/region")["population"]
    s2 =data[(data['year']==year)&(data["ages"]=="total")].dropna(how="any").set_index("state/region")["population"]
    tar =round((s1/s2),2)
    return tar.T

In [72]:
data_a =pd.DataFrame()
for y in range(1990,2014):
     data_a[y]=data_by_year(y)

In [74]:
data_a.head()

1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  ...  \
state/region                                                              ...   
AL            0.26  0.26  0.26  0.26  0.26  0.26  0.26  0.26  0.25  0.25  ...   
AK            0.32  0.32  0.31  0.31  0.31  0.31  0.30  0.31  0.31  0.31  ...   
AZ            0.27  0.27  0.27  0.27  0.26  0.26  0.26  0.26  0.26  0.27  ...   
AR            0.26  0.26  0.26  0.26  0.26  0.26  0.26  0.26  0.26  0.26  ...   
CA            0.27  0.27  0.27  0.28  0.28  0.28  0.28  0.28  0.28  0.27  ...   

              2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  
state/region                                                              
AL            0.25  0.24  0.24  0.24  0.24  0.24  0.24  0.23  0.23  0.23  
AK            0.28  0.28  0.27  0.27  0.27  0.27  0.26  0.26  0.26  0.26  
AZ            0.26  0.26  0.26  0.26  0.26  0.26  0.25  0.25  0.25  0.24  
AR            0.25  0.25  0.25  0.25  0.25  0.24  0.24  0.24  0.24  0.24  
CA            0.26  0.26  0.26  0.26  0.25  0.25  0.25  0.25  0.24  0.24  

[5 rows x 24 columns]

# 反馈
如果你对这个quiz的难度，预习的进度，以及课程目前以来的任何方面有任何建议或者问题都欢迎写在下面！