# TechX 2020 计算社科预习 Quiz 2 V1.0  (Score: 30/30)

这个测试的目的不是为了难倒大家，而是为了检验预习成果，方便我们调整接下来的预习和课程安排。同时，我们也希望你们能通过这几个练习学到的知识，并学到的coding技巧。因此，我们有如下要求：
1. 虽然我们不允许大家向别人请教 quiz 中的问题，但是你们可以在互联网上搜索已有的资源：这也是在TechX的学习过程中大家会一直做的。（PS 请别直接抄代码！请理解之后自己实现）
2. 有些题目里会给出一些变量/数据，但是我们批改的时候可能会改动它们以检测你程序的可拓展性。
3. 请在北京时间7.26 24:00之前在教学立方提交，如有事无法按时请私信自己的对应AL（在预习文档里 https://shimo.im/docs/eIy4MXRYkLoZvE2Z ）。
4. 如果感觉题目有问题或表述不清请直接在群里提出。我们有可能根据大家的提问发布V2.0 的 Quiz。

PS 问题保留了答案，但大家可以通过多种方式得到它们。

## 0. Setup

请在下面导入numpy(用np代替)，以及pandas（用pd代替）

In [2]:
import numpy as np
import pandas as pd

## 1. Array Basics
a. 创建一个shape为(10,10), 值为0~99的2D array，命名为x (应该和下图一样)(Score:2/2)

In [3]:
x = np.arange(100).reshape((10,10))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


b. 用array slicing找出x中所有5的倍数，并输出为一维array(Score:2/2)

In [4]:
print(x[:,[0,5]].flatten())

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


c. 找出array x 右上角 shape = (4, 4) 的方块和左下角shape = (2,8)的长方形，把 vertically 他们拼接成一个 shape = (4, 8)的矩阵。把这个矩阵赋值为 y。(Score:2/2)

In [5]:
square = x[:4,6:]
rectangle = x[-2:,:-2]
y = np.vstack([square, rectangle.reshape(4,4)])
print(y)

[[ 6  7  8  9]
 [16 17 18 19]
 [26 27 28 29]
 [36 37 38 39]
 [80 81 82 83]
 [84 85 86 87]
 [90 91 92 93]
 [94 95 96 97]]


d. 给y的每个值都apply这个function: $$f(x) = 3 \cdot x + 7$$(Score:2/2)

In [6]:
y = y*3 + 7
print(y)

[[ 25  28  31  34]
 [ 55  58  61  64]
 [ 85  88  91  94]
 [115 118 121 124]
 [247 250 253 256]
 [259 262 265 268]
 [277 280 283 286]
 [289 292 295 298]]


e. 创建一个和array x的shape相同的boolean mask, 每个位置的值为array x对应位置的值是否即使3的倍数又是5的倍数。把这个array称作z. (use one of / % //)(Score:2/2)

In [7]:
z = x % 15 ==0
print(z)

[[ True False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]]


In [8]:
z.shape

(10, 10)

f. 通过z来选中x中符合这些条件的数。

In [9]:
x[z]

array([ 0, 15, 30, 45, 60, 75, 90])

# 2. Pandas Basics

a. 请一句话说明concat与 merge的区别(Score:2/2)

答：concat是把两个拼接到一起，merge是根据index和信息融合dataframe

b. 用pandas导入 Data Science Handbook notebooks/data/中的 state-population.csv 文件，把它命名为df(Score:2/2)

In [13]:
df = pd.read_csv(r'C:\Users\Bertrand\Desktop\TechX预习材料\PythonDataScienceHandbook-master\PythonDataScienceHandbook-master\notebooks\data\state-population.csv')

c. 展示df的shape，它有哪些column，每个column的data type是什么？(Score:2/2)

In [14]:
df.shape

(2544, 4)

In [190]:
df.columns

Index(['state/region', 'ages', 'year', 'population'], dtype='object')

In [191]:
df.dtypes

state/region     object
ages             object
year              int64
population      float64
dtype: object

d. 展示第2301行（注意index是从0开始的）(Score:2/2)

In [192]:
df.iloc[2300,:]

state/region             WA
ages                under18
year                   2011
population      1.58471e+06
Name: 2300, dtype: object

e. 找到2002年伊利诺伊(code: IL)的总人口(Score:2/2)

In [193]:
df1 = df[(df['state/region']=='IL') & (df.year==2002) & (df1.ages=='total')]
df1

state/region   ages  year  population
646           IL  total  2002  12525556.0

f. 使用groupby等方法，计算2008年以及以后每个州18岁以下人口的平均值，输出前五个人口最多的（不包括USA，可以使用 df.sort_values()等函数 ）。(Score:2/2)

In [161]:
mean_by_states = df[(df.ages == 'under18') & (df.year >= 2008) & (df['state/region']!='USA')].groupby('state/region').mean()
top_5_df = mean_by_states.sort_values(by='population', ascending=0).head(5)
top_5_df

year    population
state/region                      
CA            2010.5  9.256073e+06
TX            2010.5  6.884565e+06
NY            2010.5  4.305392e+06
FL            2010.5  4.009472e+06
IL            2010.5  3.097347e+06

g. 找到每年总人口的maximum，minimum，以及median (用aggreagate)(Score:2/2)

In [124]:
tot = df[df.ages == 'total']
tot.groupby('year').aggregate([min, max, np.median])

population                        
            min          max     median
year                                   
1990   453690.0  249622814.0  3404386.5
1991   459260.0  252980942.0  3478761.5
1992   466251.0  256514231.0  3558201.5
1993   473081.0  259918595.0  3638524.0
1994   480283.0  263125826.0  3714782.5
1995   485160.0  266278403.0  3787617.5
1996   488167.0  269394291.0  3857868.0
1997   489452.0  272646932.0  3906221.5
1998   490787.0  275854116.0  3952313.0
1999   491780.0  279040181.0  3996367.5
2000   494300.0  282162411.0  4024223.0
2001   494657.0  284968955.0  4064995.0
2002   500017.0  287625193.0  4089875.0
2003   503453.0  290107933.0  4117170.0
2004   509106.0  292805298.0  4146101.0
2005   514157.0  295516599.0  4182742.0
2006   522667.0  298379912.0  4219239.0
2007   534876.0  301231207.0  4256672.0
2008   546043.0  304093966.0  4289878.0
2009   559851.0  306771529.0  4317074.0
2010   564222.0  309326295.0  4347698.0
2011   567329.0  311582564.0  4366869.0
2012   576626.0  313873685.0  4379730.0
2013   582658.0  316128839.0  4395295.0

h. 把df state/region  下的 IL 改成 Illinois (可以自己define一个function，也可以查询Python lambda function的使用)(Score:2/2)

In [169]:
df['state/region'] = df['state/region'].apply(lambda i: 'Illinois' if i == 'IL' else i )
df.iloc[625,:]

state/region       Illinois
ages                  total
year                   1990
population      1.14533e+07
Name: 625, dtype: object

j. Do a brief but meaningful analysis to the US population data with the tools you learned. Remember to briefly explain it with comments.(Score:2/2)

In [179]:
def get_youth_ratio_of_state(state_name):
    
    state = df[df['state/region'] == state_name]
    state_population_by_ages = state.pivot(index='year',values='population',columns='ages')
    state_population_by_ages['youth_ratio'] = state_population_by_ages['under18'] / state_population_by_ages['total']
    return state_population_by_ages['youth_ratio']

get_youth_ratio_of_state('AL')

#This function gets the ratio of under18 population against the total population of a state/region
#In the example demonstated, we can see that the YOUTH RATIO of ALABAMA is decreasing from 1990 to 2013

year
1990    0.259266
1991    0.258784
1992    0.258274
1993    0.257607
1994    0.257540
1995    0.258460
1996    0.256769
1997    0.257076
1998    0.253877
1999    0.253104
2000    0.252073
2001    0.250784
2002    0.249234
2003    0.247160
2004    0.245802
2005    0.244481
2006    0.243422
2007    0.242314
2008    0.240542
2009    0.238379
2010    0.236328
2011    0.234454
2012    0.231963
2013    0.229943
Name: youth_ratio, dtype: float64

# 反馈
如果你对这个quiz的难度，预习的进度，以及课程目前以来的任何方面有任何建议或者问题都欢迎写在下面！